ClinicaMedica/Models/Paciente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMedica.Models
{
    public class Paciente
    {
        public Paciente()
        {
            Consultas = new HashSet<Consulta>();
        }

        private string cpf { get; set; }

        public int Id { get; set; }

        [Required(ErrorMessage = "O Nome é obrigatório", AllowEmptyStrings = false)]
        [StringLength(130, MinimumLength = 3)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O Nome da mãe é obrigatório", AllowEmptyStrings = false)]
        [StringLength(130, MinimumLength = 3)]
        [Display(Name = "Nome da mãe")]
        public string NomeMae { get; set; }

        [Required(ErrorMessage = "A Data de nascimento é obrigatória")]
        [Display(Name = "Data de nascimento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date, ErrorMessage = "Data em formato inválido")]
        public DateTime DataNascimento { get; set; }

        [StringLength(14, MinimumLength = 11)]
        public string CPF {
            get
            {
                string teste = cpf;

                if ((cpf != null) && (cpf != "") && (teste.Length < 14))
                {
                    teste = Convert.ToUInt64(cpf).ToString(@"000\.000\.000\-00");
                }

                return teste;
            }
            set { cpf = value; }
        }

        [DataType(DataType.PhoneNumber)]
        [StringLength(20)]
        public string Telefone { get; set; }

        public virtual ICollection<Consulta> Consultas { get; set; }

    }
}

ClinicaMedica/Controllers/PacienteController.cs
using ClinicaMedica.Data;
using ClinicaMedica.Models;
using PagedList;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ClinicaMedica.Controllers
{
    public class PacienteController : Controller
    {
        private Context db = new Context();

        // GET: Paciente
        [Authorize(Roles = "Recepção, Médico, Laboratório")]
        public ActionResult Index(string searchString, int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.Recurso = "Atendimento > Pacientes";
            ViewBag.CampoBusca = "Nome";

            if (searchString == null)
            {
                ViewBag.Busca = "";
                return View(db.Paciente.OrderBy(p => p.Nome).ToPagedList(pageNumber, pageSize));
            }
            else
            {
                ViewBag.Busca = searchString;
                return View(db.Paciente.Where(p => p.Nome.StartsWith(searchString)).OrderBy(p => p.Nome).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Paciente/Create
        [Authorize(Roles = "Recepção")]
        public ActionResult Create()
        {
            ViewBag.Recurso = "Atendimento > Pacientes > Inclusão";
            return View();
        }

        // POST: Paciente/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Recepção")]
        public ActionResult Create([Bind(Include = "Id,Nome,NomeMae,DataNascimento,CPF,Telefone")] Paciente paciente)
        {
            bool PodeGravar = true;

            if (ModelState.IsValid)
            {
                if ((paciente.CPF != null) && (paciente.CPF != ""))
                {
                    Paciente pac = db.Paciente.Where(c => c.CPF == paciente.CPF).FirstOrDefault();

                    if (pac != null)
                    {
                        PodeGravar = false;
                        ModelState.AddModelError("", "Já existe um Paciente com este CPF");
                    }

                }                

                if (PodeGravar)
                {
                    db.Paciente.Add(paciente);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }                      
            }

            return View(paciente);
        }

        // GET: Paciente/Edit/5
        [Authorize(Roles = "Recepção")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }

            ViewBag.Recurso = "Atendimento > Pacientes > Alteração";
            return View(paciente);
        }

        // POST: Paciente/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Recepção")]
        public ActionResult Edit([Bind(Include = "Id,Nome,NomeMae,DataNascimento,CPF,Telefone")] Paciente paciente)
        {
            bool PodeGravar = true;

            if (ModelState.IsValid)
            {
                if ((paciente.CPF != null) && (paciente.CPF != ""))
                {
                    Paciente pac = db.Paciente.Where(c => c.CPF == paciente.CPF && c.Id != paciente.Id).FirstOrDefault();

                    if (pac != null)
                    {
                        PodeGravar = false;
                        ModelState.AddModelError("", "Já existe um Paciente com este CPF (" + pac.Nome + ")");
                    }

                }

                if (PodeGravar)
                {
                    db.Entry(paciente).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(paciente);
        }

        // POST: Paciente/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consulta consulta = db.Consulta.Where(c => c.PacienteId == id).FirstOrDefault();

            if (consulta == null)
            {
                Paciente paciente = db.Paciente.Find(id);
                
                db.Paciente.Remove(paciente);
                db.SaveChanges();
                return Json(new { success = true, responseText = "" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, responseText = "Este Paciente possui consultas agendadas e não pode ser excluído" }, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaMedica/Controllers/RelatorioController.cs
using ClinicaMedica.Data;
using ClinicaMedica.DTO;
using Rotativa;
using Rotativa.Options;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace ClinicaMedica.Controllers
{
    public class RelatorioController : Controller
    {
        private Context db = new Context();

        [Authorize(Roles = "Médico")]
        public ActionResult Receita(int id)
        {
            RelatorioReceitaDTO query;
            List<MedicamentoConsultaDTO> medicamentos;

            using (Context db1 = new Context())
            {
                query = (from c in db1.Consulta
                         join f in db1.Funcionario on c.FuncionarioId equals f.Id
                         join a in db1.Agenda on c.FuncionarioId equals a.Id
                         join p in db1.Paciente on c.PacienteId equals p.Id
                         where c.Id == id
                         select new RelatorioReceitaDTO
                         {
                             NomeMedico = f.Nome,
                             NomePaciente = p.Nome,
                             DataConsulta = c.DataHora,
                             CRM = a.CRM
                         })
                          .FirstOrDefault();

                medicamentos = (from c in db1.ConsultaMedicamento
                        join m in db1.Medicamento on c.MedicamentoId equals m.ID
                        where c.ConsultaId == id
                        select new MedicamentoConsultaDTO
                        {
                            NomeComercial = m.NomeComercial,
                            NomeGenerico = m.NomeGenerico,
                            Posologia = c.Posologia,
                            ID = m.ID
                        })
                          .ToList();
            }

            query.Medicamentos = medicamentos;

            if (medicamentos.Count == 0)
            {
                return View("Vazio");
            }
            else
            {
                var pdf = new ViewAsPdf
                {
                    ViewName = "Receita",
                    PageSize = Size.A4,
                    IsGrayScale = true,
                    Model = query
                };

                return pdf;

            }
        }

        [Authorize(Roles = "Médico")]
        public ActionResult Atestado(int id)
        {
            RelatorioAtestadoDTO query;
            List<TabelaDTO> cids;

            using (Context db1 = new Context())
            {   
                query = (from c in db1.Consulta
                         join f in db1.Funcionario on c.FuncionarioId equals f.Id
                         join a in db1.Agenda on c.FuncionarioId equals a.Id
                         join p in db1.Paciente on c.PacienteId equals p.Id
                         where c.Id == id
                         select new RelatorioAtestadoDTO
                         {
                             NomeMedico = f.Nome,
                             NomePaciente = p.Nome,
                             DataConsulta = c.DataHora,
                             CRM = a.CRM
                         })
                          .FirstOrDefault();

                cids = (from c in db1.ConsultaCid
                        join ci in db1.Cid on c.CidId equals ci.ID
                        where c.ConsultaId == id
                        select new TabelaDTO
                        {
                            Codigo = ci.Codigo,
                            Descricao = ci.Descricao,
                            ID = ci.ID
                        })
                          .ToList();
            }

            query.Cids = cids;

            if (cids.Count == 0)
            {
                return View("Vazio");
            }
            else
            {
                var pdf = new ViewAsPdf
                {
                    ViewName = "Atestado",
                    PageSize = Size.A4,
                    IsGrayScale = true,
                    Model = query
                };

                return pdf;
            }
        }

        [Authorize(Roles = "Médico")]
        public ActionResult Exame(int id)
        {
            RelatorioExameDTO query;
            List<ExameConsultaDTO> exames;

            using (Context db1 = new Context())
            {
                query = (from c in db1.Consulta
                         join f in db1.Funcionario on c.FuncionarioId equals f.Id
                         join a in db1.Agenda on c.FuncionarioId equals a.Id
                         join p in db1.Paciente on c.PacienteId equals p.Id
                         where c.Id == id
                         select new RelatorioExameDTO
                         {
                             NomeMedico = f.Nome,
                             NomePaciente = p.Nome,
                             DataConsulta = c.DataHora,
                             CRM = a.CRM
                         })
                          .FirstOrDefault();

                exames = (from c in db1.ConsultaExame
                        join e in db1.Exame on c.ExameId equals e.ID
                        where c.ConsultaId == id
                        select new ExameConsultaDTO
                        {
                            Codigo = e.Codigo,
                            Descricao = e.Descricao,
                            ID = e.ID,
                            Login = c.Login,
                            Senha = c.Senha,
                            NumeroPedido = c.NumeroPedido
                        })
                          .ToList();
            }

            query.Exames = exames;

            if (exames.Count == 0)
            {
                return View("Vazio");
            }
            else
            {
                var pdf = new ViewAsPdf
                {
                    ViewName = "Exame",
                    PageSize = Size.A4,
                    IsGrayScale = true,
                    Model = query
                };

                return pdf;
            }
        }

        [Authorize(Roles = "Recepção")]
        public ActionResult HistoricoConsulta(int id)
        {
            RelatorioHistoricoConsultaPacienteDTO query;
            List<RelatorioHistoricoConsultaDTO> consultas;

            using (Context db1 = new Context())
            {
                query = (from p in db1.Paciente
                         where p.Id == id
                         select new RelatorioHistoricoConsultaPacienteDTO
                         {
                             NomePaciente = p.Nome,
                             DataNascimento = p.DataNascimento,
                             NomeMae = p.NomeMae
                         })
                         .FirstOrDefault();

                consultas = (from c in db1.Consulta
                             join f in db1.Funcionario on c.FuncionarioId equals f.Id
                             join a in db1.Agenda on c.FuncionarioId equals a.Id
                             join e in db1.Especialidade on a.EspecialidadeId equals e.ID
                             where c.PacienteId == id
                             select new RelatorioHistoricoConsultaDTO
                             {
                                 NomeMedico = f.Nome,
                                 DataConsulta = c.DataHora,
                                 Especialidade = e.Descricao
                             })
                             .OrderBy(c => c.DataConsulta)
                             .ToList();
            }

            query.Consultas = consultas;

            if (consultas.Count == 0)
            {
                return View("Vazio");
            }
            else
            {
                var pdf = new ViewAsPdf
                {
                    ViewName = "HistoricoConsulta",
                    PageSize = Size.A4,
                    IsGrayScale = true,
                    Model = query
                };

                return pdf;

            }
        }        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaMedica/Views/Paciente/Create.cshtml
@model ClinicaMedica.Models.Paciente

@{
    ViewBag.Title = "Pacientes";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Recurso.cshtml")

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NomeMae, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeMae, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeMae, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control", @id = "DataNascimento" } })
            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger", @id = "valdata" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control", @id = "cpf", onchange = "RemoverValidacao('cpf')", onkeypress = "RemoverValidacao('cpf')", onkeydown = "RemoverValidacao('cpf')" } })
            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger", @id = "valcpf" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control", type = "tel", @id = "tel", onchange = "RemoverValidacao('tel')", onkeypress = "RemoverValidacao('tel')", onkeydown = "RemoverValidacao('tel')" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger", @id = "valtel" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Salvar" onclick="ValidarCampos()" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/paciente.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClinicaMedica/Views/Paciente/Edit.cshtml
@model ClinicaMedica.Models.Paciente

@{
    ViewBag.Title = "Pacientes";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Recurso.cshtml")

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NomeMae, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeMae, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeMae, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control", @id = "DataNascimento" } })
            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger", @id="valdata" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control", @id = "cpf", onchange = "RemoverValidacao('cpf')", onkeypress = "RemoverValidacao('cpf')", onkeydown = "RemoverValidacao('cpf')" } })
            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger", @id = "valcpf" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control", type = "tel", @id = "tel", onchange = "RemoverValidacao('tel')", onkeypress = "RemoverValidacao('tel')", onkeydown = "RemoverValidacao('tel')" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger", @id = "valtel" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Salvar" onclick="ValidarCampos()" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/paciente.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClinicaMedica/Views/Paciente/Index.cshtml
@model PagedList.IPagedList<ClinicaMedica.Models.Paciente>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Pacientes";
}

@using (Html.BeginForm("Index", "Paciente", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Listar.cshtml")

    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped w-auto">
                <thead>
                    <tr>
                        <th>
                            Nome
                        </th>
                        <th>
                            Nome da mãe
                        </th>
                        <th>
                            Data de nascimento
                        </th>
                        <th>
                            CPF
                        </th>
                        <th>
                            Telefone
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="id@(item.Id)">
                            <td>
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NomeMae)
                            </td>
                            <td>
                                @(item.DataNascimento.ToShortDateString())
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CPF)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefone)
                            </td>
                            <td>
                                @Html.ActionLink("Alterar", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Histórico", "HistoricoConsulta", "Relatorio", new { id = item.Id }, new { }) |
                                <a href="#" onclick="Excluir('paciente', @(item.Id))">Excluir</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        @if (@Model.PageCount != 1)
        {
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, SearchString = ViewBag.Busca }))
        }
    </div>
}

<script src="~/Scripts/validacao.js"></script>