ClinicaMedica/Models/Agenda.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMedica.Models
{
    public class Agenda
    {
        [Key]
        public int Id { get; set; }

        public virtual Funcionario Funcionario { get; set; }

        public string CRM { get; set; }

        [Display(Name = "Especialidade")]
        public int EspecialidadeId { get; set; }
        public virtual Especialidade Especialidade { get; set; }

        public bool Segunda { get; set; }
        [Display(Name = "Terça")]
        public bool Terca { get; set; }
        public bool Quarta { get; set; }
        public bool Quinta { get; set; }
        public bool Sexta { get; set; }
        [Display(Name = "Sábado")]
        public bool Sabado { get; set; }
        public bool Domingo { get; set; }

        [Display(Name = "Quantidade de conultas no dia")]
        [RangeAttribute(1, 40)]
        public int QuantidadeConsultas { get; set; }

        [Display(Name = "Tempo da consulta (em minutos)")]        
        [RangeAttribute(15, 120)]
        public int TempoConsulta { get; set; }

        [Display(Name = "Horário de início")]
        [DataType(DataType.Time)]
        public DateTime HorarioInicio { get; set; }
    }
}

ClinicaMedica/Models/Funcionario.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ClinicaMedica.Models
{

    public class Funcionario
    {
        public Funcionario()
        {
            Consultas = new HashSet<Consulta>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "O Nome é obrigatório", AllowEmptyStrings = false)]
        [StringLength(130, MinimumLength = 3)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O Login é obrigatório", AllowEmptyStrings = false)]
        [StringLength(10, MinimumLength = 3)]
        public string Login { get; set; }

        [Required(ErrorMessage = "A senha é obrigatória")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        public virtual Agenda Agenda { get; set; }

        [DisplayName("Perfil")]
        [Required(ErrorMessage = "O Perfil de acesso é obrigatório")]
        public TipoAcesso Perfil { get; set; }

        public virtual ICollection<Consulta> Consultas { get; set; }
    }

    public enum TipoAcesso
    {
        Médico = 1,
        Recepção = 2,
        Laboratório = 3,
        Supervisor = 4
    }
}

ClinicaMedica/Controllers/AgendaController.cs
using ClinicaMedica.Data;
using ClinicaMedica.DTO;
using ClinicaMedica.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web.Mvc;

namespace ClinicaMedica.Controllers
{
    public class AgendaController : Controller
    {
        private Context db = new Context();

        // GET: Consulta
        [Authorize(Roles = "Supervisor")]
        public ActionResult List(DateTime? DataPesquisa, int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            if (DataPesquisa == null)
            {
                ViewBag.Busca = DateTime.Now;
            }
            else
            {
                ViewBag.Busca = (DateTime)DataPesquisa;
            }

            DateTime dt = ViewBag.Busca;
            List<AgendasDTO> query;

            using (var db1 = new Context())
            {    
                query = (from c in db1.Consulta
                         join f in db1.Funcionario on c.FuncionarioId equals f.Id
                         where (DateTime)EntityFunctions.TruncateTime(c.DataHora) == dt
                         select new AgendasDTO {
                             IdMedico = c.FuncionarioId,
                             NomeMedico = f.Nome,
                             Data = (DateTime)EntityFunctions.TruncateTime(c.DataHora)
                         })
                         .Distinct()
                         .OrderBy(cf => cf.Data)
                         .ThenBy(cf => cf.NomeMedico).ToList();     
            }

            ViewBag.Recurso = "Atendimento > Excluir agendas";
            ViewBag.CampoBusca = "Data";
            return View(query.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirAgenda(DateTime data, int medico)
        {
            DateTime DataFinal = data;
            TimeSpan ts = new TimeSpan(23, 53, 0);
            DataFinal = DataFinal.Add(ts);

            Consulta consulta = db.Consulta.Where(c => c.FuncionarioId == medico && 
                                                   c.DataHora >= data &&
                                                   c.DataHora <= DataFinal &&
                                                   c.PacienteId != null).FirstOrDefault();

            if (consulta == null)
            {
                List<Consulta> consultas = db.Consulta.Where(c => c.FuncionarioId == medico &&
                                                             c.DataHora >= data &&
                                                             c.DataHora <= DataFinal).ToList();

                for (int i = 0; i <= consultas.Count - 1; i++)
                {
                    db.Consulta.Remove(consultas[i]);
                }

                db.SaveChanges();
                return Json(new { success = true, responseText = "" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, responseText = "Esta agenda não pode ser excluída, pois existem consultas agendadas." }, JsonRequestBehavior.AllowGet);
            }
        }


        // GET: Consulta/Create
        [Authorize(Roles = "Supervisor")]
        public ActionResult Create()
        {
            AgendaDTO agenda = new AgendaDTO();

            using (var ctx =  new Context())
            {
                var maxObject = ctx.Consulta.OrderByDescending(c => c.DataHora).Select(c => c.DataHora).FirstOrDefault();

                if (maxObject == DateTime.MinValue)
                {
                    agenda.DataInicio = (DateTime.Today).AddDays(1);
                }
                else
                {
                    agenda.DataInicio = Convert.ToDateTime(maxObject).AddDays(1);
                }
            }

            agenda.DataTermino = agenda.DataInicio.AddDays(7);

            ViewBag.Recurso = "Atendimento > Gerar agendas";
            return View(agenda);
        }

        // POST: Consulta/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Supervisor")]
        public ActionResult Create([Bind(Include = "DataInicio, DataTermino")] AgendaDTO agenda)
        {
            if (ModelState.IsValid)
            {
                // buscar medicos que atendem nos dias da semana
                List<Funcionario> medicosSeg = db.Funcionario.Include(a => a.Agenda).Where(f => f.Agenda.Segunda.Equals(true)).ToList();
                List<Funcionario> medicosTer = db.Funcionario.Include(a => a.Agenda).Where(f => f.Agenda.Terca.Equals(true)).ToList();
                List<Funcionario> medicosQua = db.Funcionario.Include(a => a.Agenda).Where(f => f.Agenda.Quarta.Equals(true)).ToList();
                List<Funcionario> medicosQui = db.Funcionario.Include(a => a.Agenda).Where(f => f.Agenda.Quinta.Equals(true)).ToList();
                List<Funcionario> medicosSex = db.Funcionario.Include(a => a.Agenda).Where(f => f.Agenda.Sexta.Equals(true)).ToList();
                List<Funcionario> medicosSab = db.Funcionario.Include(a => a.Agenda).Where(f => f.Agenda.Sabado.Equals(true)).ToList();
                List<Funcionario> medicosDom = db.Funcionario.Include(a => a.Agenda).Where(f => f.Agenda.Domingo.Equals(true)).ToList();

                List<Funcionario> dia = null;

                for (var day = agenda.DataInicio; day <= agenda.DataTermino; day = day.AddDays(1))
                {
                    switch (day.DayOfWeek)
                    {
                        case DayOfWeek.Sunday:
                            dia = medicosDom;
                            break;

                        case DayOfWeek.Monday:
                            dia = medicosSeg;
                            break;

                        case DayOfWeek.Tuesday:
                            dia = medicosTer;
                            break;

                        case DayOfWeek.Wednesday:
                            dia = medicosQua;
                            break;

                        case DayOfWeek.Thursday:
                            dia = medicosQui;
                            break;

                        case DayOfWeek.Friday:
                            dia = medicosSex;
                            break;

                        case DayOfWeek.Saturday:
                            dia = medicosSab;
                            break;
                    }


                    foreach (Funcionario Medico in dia)
                    {
                        DateTime HoraInicio = Medico.Agenda.HorarioInicio;

                        DateTime today = day;
                        TimeSpan newTime = new TimeSpan(Medico.Agenda.HorarioInicio.Hour, Medico.Agenda.HorarioInicio.Minute, 0);
                        today = today.Date + newTime;

                        for (int i = 0; i < Medico.Agenda.QuantidadeConsultas; i++)
                        {                           
                            Consulta cons = new Consulta();
                            cons.FuncionarioId = Medico.Id;
                            cons.DataHora = today;  
                            db.Consulta.Add(cons);
                            db.SaveChanges();

                           today = today.AddMinutes(Medico.Agenda.TempoConsulta);
                        }
                    }
                }
            }

            return RedirectToAction("Index", "Principal");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaMedica/Controllers/FuncionarioController.cs
using ClinicaMedica.Data;
using ClinicaMedica.DTO;
using ClinicaMedica.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;
using System;

namespace ClinicaMedica.Controllers
{
    public class FuncionarioController : Controller
    {
        private Context db = new Context();

        // GET: Funcionario
        [Authorize(Roles = "Supervisor")]
        public ActionResult Index(string searchString, int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.Recurso = "Recursos > Funcionário";
            ViewBag.CampoBusca = "Nome";

            if (searchString == null)
            {
                ViewBag.Busca = "";
                return View(db.Funcionario.Include(f => f.Agenda).OrderBy(f => f.Nome).ToPagedList(pageNumber, pageSize));
            }
            else
            {
                ViewBag.Busca = searchString;
                return View(db.Funcionario.Include(f => f.Agenda).Where(f => f.Nome.StartsWith(searchString)).OrderBy(f => f.Nome).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Funcionario/Create
        [Authorize(Roles = "Supervisor")]
        public ActionResult Create()
        {
            ViewBag.EspecialidadeId = new SelectList(db.Especialidade, "ID", "Descricao");   
            ViewBag.Recurso = "Recursos > Funcionários > Inclusão";
            return View();
        }

        // POST: Funcionario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Supervisor")]
        public ActionResult Create([Bind(Include = "ID,Nome,Login,Senha,Perfil," +
                                                   "Agenda")] Funcionario funcionario, string EspecialidadeId)
        {
            if (funcionario.Perfil == TipoAcesso.Médico)
            {
                funcionario.Agenda.EspecialidadeId = Int32.Parse(EspecialidadeId);
            }
            else
            {
                funcionario.Agenda = null;
            }

            Funcionario funcionarioExiste = db.Funcionario.Where(f => f.Login.Equals(funcionario.Login)).FirstOrDefault();

            if (funcionarioExiste != null)
            {
                ModelState.AddModelError("", "Já existe um Funcionário com este Login");
            }
            else
            {
                db.Funcionario.Add(funcionario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(funcionario);
        }

        // GET: Funcionario/Edit/5
        [Authorize(Roles = "Supervisor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Funcionario funcionario = db.Funcionario.Include(a => a.Agenda).Where(f => f.Id == id).FirstOrDefault();

            if (funcionario == null)
            {
                return HttpNotFound();
            }

            ViewBag.EspecialidadeId = new SelectList(db.Especialidade, "ID", "Descricao");
            ViewBag.Recurso = "Recursos > Funcionários > Alteração";
            return View(funcionario);
        }

        // POST: Funcionario/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Login,Perfil,Agenda")] Funcionario funcionario, string EspecialidadeId)
        {
            ViewBag.EspecialidadeId = new SelectList(db.Especialidade, "ID", "Descricao");
            Funcionario funcionarioExiste = db.Funcionario.Where(f => f.Login.Equals(funcionario.Login) && f.Id != funcionario.Id).FirstOrDefault();
            int QtdConsulta = 0;
            ViewBag.MsgErro = "";

            if (funcionarioExiste != null)
            {
                ModelState.AddModelError("", "Já existe um Funcionário com este Login");
                return View(funcionario);
            }
            else
            { 
                if (funcionario.Perfil == TipoAcesso.Médico)
                {
                    int EspecialidadeOld = db.Agenda.Where(a => a.Id == funcionario.Id).Select(a => a.EspecialidadeId).First();

                    if (EspecialidadeOld != Int32.Parse(EspecialidadeId))
                    {
                        QtdConsulta = db.Consulta.Where(c => c.FuncionarioId == funcionario.Id && c.PacienteId != null).Select(c => c.Id).First();
                    }

                    if (QtdConsulta > 0)
                    {
                        ViewBag.MsgErro = "A Especialidade não pode ser alterada, pois o médico possui consultas agendadas.";
                        return View(funcionario);
                    }

                    funcionario.Agenda.Id = funcionario.Id;
                    funcionario.Agenda.EspecialidadeId = Int32.Parse(EspecialidadeId);
                    db.Entry(funcionario.Agenda).State = EntityState.Modified;
                }
                else
                {
                    funcionario.Agenda = null;
                }

                string senha = db.Funcionario.Where(f => f.Id == funcionario.Id).Select(f => f.Senha).FirstOrDefault();
                funcionario.Senha = senha;

                db.Entry(funcionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }                
        }

        // POST: Funcionario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consulta consulta = db.Consulta.Where(c => c.FuncionarioId == id).FirstOrDefault();

            if (consulta == null)
            {
                Funcionario funcionario = db.Funcionario.Find(id);
                Agenda agenda = db.Agenda.Find(id);

                if (funcionario.Nome != "supervisor")
                {
                    db.Agenda.Remove(agenda);
                    db.Funcionario.Remove(funcionario);
                    db.SaveChanges();
                    return Json(new { success = true, responseText = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, responseText = "O Supervisor do sistema não pode ser excluído" }, JsonRequestBehavior.AllowGet);
                }             
            }
            else
            {
                return Json(new { success = false, responseText = "Este Funcionário possui consultas agendadas e não pode ser excluído" }, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaMedica/Views/Funcionario/Agenda.cshtml
@model ClinicaMedica.Models.Funcionario


@using (Html.BeginForm())
{

<div class="form-horizontal" id="agenda_crm" hidden>

    <h3>Agenda</h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.CRM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Agenda.CRM, new { htmlAttributes = new { @class = "form-control", @id = "crm", onchange = "RemoverValidacao('crm')", onkeypress = "RemoverValidacao('crm')", onkeydown = "RemoverValidacao('crm')" } })
            @Html.ValidationMessageFor(model => model.Agenda.CRM, "", new { @class = "text-danger", id = "valcrm" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.EspecialidadeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("EspecialidadeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Agenda.EspecialidadeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.Segunda, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Agenda.Segunda, new { @id = "ckbSeg", onclick = "RemoverValidacao('dias')" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.Terca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Agenda.Terca, new { @id = "ckbTer", onclick = "RemoverValidacao('dias')" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.Quarta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Agenda.Quarta, new { @id = "ckbQua", onclick = "RemoverValidacao('dias')" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.Quinta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Agenda.Quinta, new { @id = "ckbQui", onclick = "RemoverValidacao('dias')" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.Sexta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Agenda.Sexta, new { @id = "ckbSex", onclick = "RemoverValidacao('dias')" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.Sabado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Agenda.Sabado, new { @id = "ckbSab", onclick = "RemoverValidacao('dias')" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.Domingo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Agenda.Domingo, new { @id = "ckbDom", onclick = "RemoverValidacao('dias')" })
            @Html.ValidationMessageFor(model => model.Agenda.Domingo, "", new { @class = "text-danger", id = "valdias" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.QuantidadeConsultas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Agenda.QuantidadeConsultas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Agenda.QuantidadeConsultas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.TempoConsulta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Agenda.TempoConsulta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Agenda.TempoConsulta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Agenda.HorarioInicio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Agenda.HorarioInicio, new { htmlAttributes = new { @class = "form-control", type = "time" } })
            @Html.ValidationMessageFor(model => model.Agenda.HorarioInicio, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
    
   
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClinicaMedica/Views/Funcionario/Create.cshtml
@model ClinicaMedica.Models.Funcionario

@{
    ViewBag.Title = "Funcionários";
}

@using (Html.BeginForm("Create", "Funcionario", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmFunc" }))
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Recurso.cshtml")

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Perfil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Perfil, // Model field that will be used to store user selection
                              "", // Text for the first 'default' option
                              new { @class = "form-control", id="cmbPerfil", onchange = "perfil_change(this)" })  @* A class name to assign to "select" tag *@
                            @Html.ValidationMessageFor(model => model.Perfil, "", new { @class = "text-danger", id = "valperfil" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Partial("Agenda", Model)
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" value="Salvar" onclick="ValidarCampos()" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/funcionario.js"></script>

ClinicaMedica/Views/Funcionario/Edit.cshtml
@model ClinicaMedica.Models.Funcionario

@{
    ViewBag.Title = "Funcionários";
}

@using (Html.BeginForm("Edit", "Funcionario", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmFunc" }))
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Recurso.cshtml")

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @if (ViewBag.MsgErro != "")
    {
        <p id="msgerro">@ViewBag.MsgErro</p>;
    }

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Perfil, htmlAttributes: new { @class = "hidden" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Perfil, "", new { @class = "hidden", id = "cmbPerfil", onchange = "perfil_change(this)" })
            @Html.ValidationMessageFor(model => model.Perfil, "", new { @class = "text-danger", id = "valperfil" })
        </div>
    </div>

    <div class="form-group">
        @Html.Partial("Agenda", Model)
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Salvar" onclick="ValidarCampos()" class="btn btn-default" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/funcionario.js"></script>

ClinicaMedica/Views/Funcionario/Index.cshtml
@model PagedList.IPagedList<ClinicaMedica.Models.Funcionario>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Funcionários";
}

@using (Html.BeginForm("Index", "Funcionario", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Listar.cshtml")

    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped w-auto">
                <thead>
                    <tr>
                        <th>
                            Nome
                        </th>
                        <th>
                            Login
                        </th>
                        <th>
                            Perfil
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="id@(item.Id)">
                            <td>
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Login)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Perfil)
                            </td>
                            @if (User.IsInRole("Supervisor"))
                            {
                                <td>

                                    @Html.ActionLink("Alterar", "Edit", new { id = item.Id }) |
                                    <a href="#" onclick="Excluir('funcionario',@(item.Id))">Excluir</a>

                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        @if (@Model.PageCount != 1)
        {
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, SearchString = ViewBag.Busca }))
        }
    </div>
}