ClinicaMedica/Models/Exame.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClinicaMedica.Models
{
    public class Exame
    {
        public Exame()
        {
            ConsultaExames = new HashSet<ConsultaExame>();
        }

        public int ID { get; set; }

        [Required(ErrorMessage = "O código do Exame é obrigatório", AllowEmptyStrings = false)]
        [StringLength(10, MinimumLength = 3)]
        [Display(Name = "Código")]
        public string Codigo { get; set; }

        [Required(ErrorMessage = "A Descrição do Exame é obrigatória", AllowEmptyStrings = false)]
        [StringLength(250, MinimumLength = 1)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        public virtual ICollection<ConsultaExame> ConsultaExames { get; set; }
    }
}

ClinicaMedica/Controllers/ExameController.cs
using ClinicaMedica.Data;
using ClinicaMedica.Models;
using PagedList;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ClinicaMedica.Controllers
{
    public class ExameController : Controller
    {
        private Context db = new Context();

        // GET: Exame
        [Authorize(Roles = "Supervisor,Médico,Laboratório")]
        public ActionResult Index(string searchString, int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.Recurso = "Tabelas > Exames";
            ViewBag.CampoBusca = "Código";

            if (searchString == null)
            {
                ViewBag.Busca = "";
                return View(db.Exame.OrderBy(c => c.Codigo).ToPagedList(pageNumber, pageSize));
            }
            else
            {
                ViewBag.Busca = searchString;
                return View(db.Exame.Where(c => c.Codigo.StartsWith(searchString)).OrderBy(c => c.Codigo).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Exame/Create
        [Authorize(Roles = "Supervisor")]
        public ActionResult Create()
        {
            ViewBag.Recurso = "Tabelas > Exames > Inclusão";
            return View();
        }

        // POST: Exame/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Supervisor")]
        public ActionResult Create([Bind(Include = "ID,Codigo,Descricao")] Exame exame)
        {
            if (ModelState.IsValid)
            {
                Exame exameExiste = db.Exame.Where(e => e.Codigo.Equals(exame.Codigo)).FirstOrDefault();

                if (exameExiste == null)
                {
                    db.Exame.Add(exame);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Já existe um Exame com este Código");
                }
            }

            return View(exame);
        }

        // GET: Exame/Edit/5
        [Authorize(Roles = "Supervisor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exame exame = db.Exame.Find(id);
            if (exame == null)
            {
                return HttpNotFound();
            }

            ViewBag.Recurso = "Tabelas > Exames > Alteração";
            return View(exame);
        }

        // POST: Exame/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Supervisor")]
        public ActionResult Edit([Bind(Include = "ID,Codigo,Descricao")] Exame exame)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exame).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exame);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            ConsultaExame consulta = db.ConsultaExame.Where(cc => cc.ExameId == id).FirstOrDefault();

            if (consulta == null)
            {
                Exame exame = db.Exame.Find(id);
                db.Exame.Remove(exame);
                db.SaveChanges();
                return Json(new { success = true, responseText = "" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, responseText = "Este Exame está sendo utilizado e não pode ser excluído." }, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaMedica/Views/Exame/Create.cshtml
@model ClinicaMedica.Models.Exame

@{
    ViewBag.Title = "Exames";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Recurso.cshtml")

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClinicaMedica/Views/Exame/Edit.cshtml
@model ClinicaMedica.Models.Exame

@{
    ViewBag.Title = "Exames";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Recurso.cshtml")

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClinicaMedica/Views/Exame/Index.cshtml
@model PagedList.IPagedList<ClinicaMedica.Models.Exame>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Exames";
}

@using (Html.BeginForm("Index", "Exame", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Listar.cshtml")

    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped w-auto">
                <thead>
                    <tr>
                        <th>
                            Código
                        </th>
                        <th>
                            Descrição
                        </th>
                        <th>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="id@(item.ID)">
                            <td>
                                @Html.DisplayFor(modelItem => item.Codigo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descricao)
                            </td>
                            @if (User.IsInRole("Supervisor"))
                            {
                                <td>
                                    @Html.ActionLink("Alterar", "Edit", new { id = item.ID }) |
                                    <a href="#" onclick="Excluir('exame', @(item.ID))">Excluir</a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        @if (@Model.PageCount != 1)
        {
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, SearchString = ViewBag.Busca }))
        }
    </div>
}